### ISSUE TITLE
Release dparse with Piplock support

### ISSUE THREAD

**Issue by kxepal** [pyupio/dparse#20]
Currently, Piplock support is only available on master, not in 0.2.1 release:
https://github.com/pyupio/dparse/commit/9cd1830f823bef6b41625705a58f9aa4502faa03

However, pyupio already uses this feature in 0.9.0 release:
https://github.com/pyupio/pyup/blob/0.9.0/pyup/requirements.py#L148

This makes pyupio broken.

**Comment by jayfk** [comment]
Thanks for pointing that out, new release will come tomorrow!

**Comment by jayfk** [comment]
Leaving this open as a remainder to write some integration tests on stuff like that.
