### ISSUE TITLE
Passing the baton?

### ISSUE THREAD

**Issue by pombredanne** [pyupio/dparse#40]
@jayfk @Jwomers it looks like this repo is needing some love. 
What's the status? I use it in scancode-toolkit (and I contributed some in the past and I am a contributor). I'd like to volunteer to take over its maintenance entirely. What do you think?
If you prefer discussing offline, I can be reached @ pombredanne@gmail.com

**Comment by rafaelpivato** [comment]
I see you were added as a collaborator. Closing this... :sunflower:
