### ISSUE TITLE
Drop support for older Python

### ISSUE THREAD

**Issue by pombredanne** [pyupio/dparse#41]
It is time to drop support (at least in the CI) for older Python 3 versions before 3.4 IMHO (and later Python 2.7)

**Comment by hugovk** [comment]
👍 

Python 2.7 and 3.0 - 3.4 are EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

They're also little used. Here's the pip installs for dparse from PyPI for December 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  42.60% |    88,825 |
| 3.6      |  31.92% |    66,553 |
| 3.5      |  10.27% |    21,412 |
| 2.7      |   8.25% |    17,203 |
| 3.8      |   6.15% |    12,831 |
| 3.4      |   0.46% |       954 |
| null     |   0.29% |       607 |
| 2.6      |   0.05% |       110 |
| 3.9      |   0.01% |        22 |
| Total    |         |   208,517 |

Source: `pip install -U pypistats && pypistats python_minor dparse --last-month`

**Comment by pombredanne** [comment]
@hugovk thanks!

**Comment by rafaelpivato** [comment]
Love those details. Thanks for that. We did this with #43
