### ISSUE TITLE
GHSL-2021-111

### ISSUE THREAD

**Issue by kevinbackhouse** [pyupio/dparse#50]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to GHSL-2021-111.

Thank you,  
Kevin Backhouse
GitHub Security Lab

**Comment by ptmcg** [comment]
Is there any activity on this issue? dparse is used in flask-restx, which is currently failing ossaudit security check due to this project. (See https://github.com/python-restx/flask-restx/pull/463.)

**Comment by kevinbackhouse** [comment]
This is a ReDoS issue, so it's low severity. It was [fixed](https://github.com/nexB/dparse2/commit/3aecaac9a1bde349418810a320a7e5ec31ee276a) in the [nexB fork](https://github.com/nexB/dparse) but not here. I didn't publish our advisory because the issue hadn't been fully resolved, but it's been almost a year now so I'll publish it. It should appear [here](https://securitylab.github.com/advisories) in the next few days.

**Comment by yeisonvargasf** [comment]
@ptmcg this will be fixed in the next few days. Thanks @kevinbackhouse for the patience here, I'll address that before the advisory is published.

**Comment by yeisonvargasf** [comment]
@kevinbackhouse I've created the draft security advisory, and I invited you.

**Comment by yeisonvargasf** [comment]
I am closing this, thanks @kevinbackhouse!
