### ISSUE TITLE
Pipfile invalid specifier

### ISSUE THREAD

**Issue by gg-mmill** [pyupio/dparse#60]
Hello,

* Dependency Parser version:  0.6.2
* Python version: any
* Operating System: any

### Description

Although not fully conform to the spec, pipenv support having package versions defined as a simple version number, e.g. "1.2.3".

Would you be interested in PR to support such a format ?

### What I Did

When running the following commands:
```
>>> from dparse import parse, filetype
>>> content  = """
        [[source]]
        
        url = "http://some.pypi.mirror.server.org/simple"
        verify_ssl = false
        name = "pypi"
        
        [packages]
        djangorestframework = "1.25.1"
        """
>>> parse(content, file_type=filetypes.pipfile)
```

dparse raise the following exception (from the python `packaging` module:  
```
InvalidSpecifier: Invalid specifier: '1.25.1'
```

**Comment by yeisonvargasf** [comment]
Hi @gg-mmill, we would like to match the spec as much as possible, but if we have strong arguments about supporting this format, we will merge it.

**Comment by gg-mmill** [comment]
Thanks for the fast feedback. I'm afraid I have no real argument, outside that's a feature we would be interested in (because some people manually edit `Pipfile`s, and this case does arise sometimes).

But you are right that without a clear specification for what the result should be, it may be preferable to not include it in this library, we will make adaptations on our side  ;)
