### ISSUE TITLE
Please release a new version which drops toml as dependency

### ISSUE THREAD

**Issue by oz123** [pyupio/dparse#65]
This commit 31a1d5b0442b124c2c45a0dfae6632788e3c9cea is really significant for pipenv which vendors dparse.
I'd be happy to see this included in an official version.

**Comment by oz123** [comment]
ping

**Comment by yeisonvargasf** [comment]
Hi @oz123, I hope everything is going great; I'm sorry for not getting back to you sooner.

We'll include this in a coming release in the following weeks. Let me know if you need this included as soon as possible; if so, we are open to considering releasing it before.

**Comment by yeisonvargasf** [comment]
@oz123, thanks for explaining, that makes sense; I'll launch a release in the following (~3) days.

**Comment by oz123** [comment]
Thank you very much.
If you don't mind, for the next versions, please use lazy imports when adding new dependencies.
As you already do for the conda parser:

```
class CondaYMLParser(Parser):
    """

    """

    def parse(self):
        """

        :return:
        """
        import yaml
        try:
        ...
```

This way we can include dparse without the optional dependency of yaml which is not required for pipenv.
